// Generated by CoffeeScript 1.6.3
var define;

define = (function(root) {
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    if (typeof module === 'object' && module.exports) {
      return function(factory) {
        return module.exports = factory();
      };
    } else {
      return function(factory) {
        return root.Observable = factory();
      };
    }
  }
})(this);

define(function() {
  var Observable;
  return Observable = (function() {
    function Observable(initial) {
      if (!this instanceof Observable) {
        return new Observable(initial);
      }
      this.previousValue = void 0;
      this.value = initial;
      this.observers = [];
    }

    Observable.prototype.set = function(v) {
      var fn, _i, _len, _ref, _results;
      if (v === this.value) {
        return;
      }
      this.previousValue = this.value;
      this.value = v;
      _ref = this.observers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        fn = _ref[_i];
        _results.push(fn.call(this, this.value, this.previousValue));
      }
      return _results;
    };

    Observable.prototype.get = function() {
      return this.value;
    };

    Observable.prototype.watch = function(cb) {
      if (typeof cb !== 'function') {
        return;
      }
      return this.observers.push(cb);
    };

    return Observable;

  })();
});
